import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {z} from 'zod';
import {ShopSchema, GenerationJobSchema, RevisionManifestSchema, PublicationOperationSchema} from '../src/domain/records.ts';
import {PublishRequestSchema, PublicationStatusSchema} from '../src/publishing/service.ts';
import {CreateShopSchema, SubmitJobSchema, DesignSchema} from '../src/domain/shops.ts';
import {ChallengeResponseSchema, SessionResponseSchema, PreviewResponseSchema} from '../src/api/contracts.ts';

// Generate wire types from the same runtime schemas used by the builder.
function type(schema: any): string {
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map((value: unknown) => JSON.stringify(value)).join(' | ');
  if (schema.anyOf || schema.oneOf) return (schema.anyOf ?? schema.oneOf).map(type).join(' | ');
  if (Array.isArray(schema.type)) return schema.type.map((value: string) => type({...schema, type: value})).join(' | ');
  if (schema.type === 'array') return `Array<${type(schema.items)}>`;
  if (schema.type === 'object') return `{ ${Object.entries(schema.properties ?? {}).map(([key, value]) => `${JSON.stringify(key)}${schema.required?.includes(key) ? '' : '?'}: ${type(value)};`).join(' ')} }`;
  if (['string', 'number', 'boolean', 'null'].includes(schema.type)) return schema.type;
  if (schema.type === 'integer') return 'number';
  throw new Error(`Unsupported contract schema: ${JSON.stringify(schema)}`);
}
const schemas = {Publication: PublicationOperationSchema, PublishRequest: PublishRequestSchema, PublicationStatus: PublicationStatusSchema, Shop: ShopSchema, GenerationJob: GenerationJobSchema, Revision: RevisionManifestSchema, Design: DesignSchema,
  CreateShop: CreateShopSchema, SubmitJob: SubmitJobSchema, ChallengeResponse: ChallengeResponseSchema, SessionResponse: SessionResponseSchema, PreviewResponse: PreviewResponseSchema};
const output = '// Generated by merxet-storefront-builder: npm run seller-contracts:sync. Do not edit.\n' +
  Object.entries(schemas).map(([name, schema]) => `export type ${name} = ${type(z.toJSONSchema(schema))};\n`).join('');
const target = new URL('../../merxet-seller/src/lib/storefront/contracts.ts', import.meta.url);
if (process.argv.includes('--check')) {
  if ((await readFile(target, 'utf8')).replaceAll('\r\n', '\n') !== output) throw new Error('Seller builder contracts are stale');
} else { await mkdir(new URL('./', target), {recursive: true}); await writeFile(target, output); }
