async (page) => {
  const check = (value, message) => { if (!value) throw new Error(message); };
  const preview = page.frameLocator('iframe');
  await preview.locator('.shop-product-card').first().waitFor();
  await page.screenshot({path: 'output/playwright/phase5-desktop.png'});
  await page.getByRole('button', {name: 'Collapse Design panel', exact: true}).click();
  await preview.getByRole('link', {name: 'Shop all', exact: true}).first().click();
  await preview.getByRole('searchbox', {name: 'Search products'}).fill('olive');
  check(await preview.locator('.shop-product-card').count() === 1, 'Search must filter products');
  await preview.getByRole('link', {name: 'View Extra Virgin Olive Oil'}).click();
  await preview.getByRole('heading', {name: 'Extra Virgin Olive Oil', exact: true}).waitFor();
  const buyerLink = await preview.getByRole('link', {name: 'Open in Merxet', exact: true}).getAttribute('href');
  check(buyerLink === 'https://app.merxet.com/#AAAAAAAAAAAAAAAAAAAAAAlIZWNPYBR6aCU0P8t0rZNA2', 'Buyer identity must be preserved');
  const frame = page.frames().find(value => value.url().startsWith('http://127.0.0.1:4183/'));
  await frame.evaluate(() => { window.__phase5Marker = 'preserved'; window.scrollTo(0, 180); });
  const before = await frame.evaluate(() => ({url: location.href, scroll: scrollY}));
  await page.locator('.storefront-workspace-header').getByRole('button', {name: 'Show Design panel'}).click();
  await page.getByRole('textbox', {name: 'What would you like to change?'}).fill('Give the product photos more space.');
  const handle = page.getByRole('button', {name: 'Move Design panel'}), box = await handle.boundingBox();
  await page.mouse.move(box.x + 70, box.y + 15); await page.mouse.down(); await page.mouse.move(1000, 260, {steps: 12});
  check(await page.getByTestId('preview-drag-shield').count() === 1, 'Dragging must shield the iframe');
  await page.mouse.up(); check(await page.getByTestId('preview-drag-shield').count() === 0, 'Shield must be released');
  await page.getByRole('button', {name: 'Collapse Design panel', exact: true}).click();
  await page.locator('.storefront-workspace-header').getByRole('button', {name: 'Show Design panel'}).click();
  const after = await frame.evaluate(() => ({url: location.href, scroll: scrollY, marker: window.__phase5Marker}));
  check(after.url === before.url && after.scroll === before.scroll && after.marker === 'preserved', 'Panel interactions must preserve the preview document');
  check(await page.getByRole('textbox', {name: 'What would you like to change?'}).inputValue() === 'Give the product photos more space.', 'Prompt must survive collapse');
  await page.getByRole('button', {name: 'Mobile preview', exact: true}).click();
  check(Math.round((await page.locator('iframe').boundingBox()).width) === 390, 'Mobile preview width');
  await page.getByRole('button', {name: 'Desktop preview', exact: true}).click();
  const newTabPromise = page.context().waitForEvent('page');
  await page.getByRole('link', {name: 'Open preview in new tab'}).click();
  const tab = await newTabPromise; await tab.waitForLoadState(); await tab.locator('.shop-product-card').first().waitFor();
  await tab.goto(tab.url() + 'products/lIZWNPYBR6aCU0P8t0rZNA');
  await tab.getByRole('heading', {name: 'Extra Virgin Olive Oil', exact: true}).waitFor(); await tab.reload();
  await tab.getByRole('heading', {name: 'Extra Virgin Olive Oil', exact: true}).waitFor(); await tab.close();
  await page.getByRole('button', {name: 'Generate revision', exact: true}).click();
  await page.getByText('Creating design', {exact: true}).waitFor();
  check(await frame.evaluate(() => window.__phase5Marker) === 'preserved', 'Current preview must survive a new build');
  await page.getByRole('button', {name: 'Draft 2 ready — View'}).waitFor({timeout: 30000});
  check(await page.getByRole('combobox', {name: 'Preview revision'}).inputValue() === await page.getByRole('combobox', {name: 'Preview revision'}).locator('option').first().getAttribute('value'), 'Ready revision must not replace the current preview');
  await page.getByRole('button', {name: 'Draft 2 ready — View'}).click();
  await page.getByText('Based on Draft 2', {exact: true}).waitFor();
  await preview.locator('.shop-product-card').first().waitFor();
  await page.screenshot({path: 'output/playwright/phase5-revision-history.png'});
  console.log('Desktop checks passed: browsing, buyer link, iframe state, dragging/collapse, sizing, protected new tab, direct reload and revision generation.');
}
