async (page) => {
  const assert = (value, message) => { if (!value) throw new Error(message); };
  await page.getByRole('button', {name: 'Draft 1 ready — View', exact: true}).waitFor({timeout: 60000});
  await page.getByRole('button', {name: 'Draft 1 ready — View', exact: true}).click();
  await page.frameLocator('iframe').getByRole('heading', {level: 1}).waitFor();
  await page.getByRole('button', {name: 'Publish draft', exact: true}).click();
  await page.getByRole('button', {name: 'Cancel publication', exact: true}).click();
  assert(await page.getByText('Your shop is private', {exact: true}).isVisible(), 'Cancel must leave shop private');
  const posts = []; let loseResponse = true;
  await page.route('**/api/v1/testnet/shops/*/publications', async route => {
    if (route.request().method() !== 'POST') return route.continue();
    posts.push({key: route.request().headers()['idempotency-key'], body: route.request().postData()});
    if (loseResponse) { loseResponse = false; await route.fetch(); await route.abort(); } else await route.continue();
  });
  await page.getByRole('button', {name: 'Publish draft', exact: true}).click();
  await page.getByRole('button', {name: 'Confirm publish', exact: true}).click();
  await page.getByRole('button', {name: 'Retry request', exact: true}).waitFor();
  await page.getByRole('button', {name: 'Retry request', exact: true}).click();
  await page.getByText('Draft 1 published', {exact: true}).waitFor({timeout: 60000});
  assert(posts.length === 2 && JSON.stringify(posts[0]) === JSON.stringify(posts[1]), 'Publish retry must replay identical key/body');
  const liveUrl = await page.getByRole('link', {name: 'Open live shop'}).getAttribute('href');
  const live = await page.context().newPage(); await live.goto(liveUrl);
  await live.getByRole('heading', {level: 1}).waitFor();
  const a = (await live.request.get(liveUrl)).headers()['x-merxet-revision'];
  await page.getByLabel('What would you like to change?').fill('Make the header smaller.');
  await page.getByRole('button', {name: 'Generate revision', exact: true}).click();
  assert((await live.request.get(liveUrl)).headers()['x-merxet-revision'] === a, 'A must remain public during generation');
  await page.getByRole('button', {name: 'Draft 2 ready — View', exact: true}).waitFor({timeout: 60000});
  await page.getByRole('button', {name: 'Draft 2 ready — View', exact: true}).click();
  assert((await live.request.get(liveUrl)).headers()['x-merxet-revision'] === a, 'Selecting B must not publish it');
  await page.getByRole('button', {name: 'Publish draft', exact: true}).click();
  await page.getByRole('group', {name: 'Confirm publication'}).getByText('Draft 1', {exact: true}).waitFor();
  await page.getByRole('button', {name: 'Confirm publish', exact: true}).click();
  await page.getByText('Draft 2 published', {exact: true}).waitFor({timeout: 60000});
  const b = (await live.request.get(liveUrl)).headers()['x-merxet-revision']; assert(a !== b, 'B must now be public');
  await live.goto(liveUrl + 'products/lIZWNPYBR6aCU0P8t0rZNA');
  await live.getByRole('heading', {name: 'Extra Virgin Olive Oil', exact: true}).waitFor();
  await live.reload(); await live.getByRole('heading', {name: 'Extra Virgin Olive Oil', exact: true}).waitFor();
  assert(await live.locator('a[href*="app.merxet.com"]').count() > 0, 'Buyer link missing');
  await page.screenshot({path: 'output/playwright/phase6-published.png'});
  await page.reload(); await page.getByRole('button', {name: 'Sign in with wallet', exact: true}).click();
  await page.getByText('Draft 2 published', {exact: true}).waitFor();
  const options = await page.getByLabel('Preview revision').locator('option').all();
  await page.getByLabel('Preview revision').selectOption(await options[0].getAttribute('value'));
  await page.getByRole('button', {name: 'Roll back to this draft', exact: true}).click();
  await page.getByRole('button', {name: 'Cancel publication', exact: true}).click();
  assert((await live.request.get(liveUrl)).headers()['x-merxet-revision'] === b, 'Cancel rollback must retain B');
  await page.setViewportSize({width: 390, height: 844});
  await page.getByRole('button', {name: 'Roll back to this draft', exact: true}).click();
  await page.screenshot({path: 'output/playwright/phase6-mobile-rollback.png'});
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile overflow');
  await page.getByRole('button', {name: 'Confirm rollback', exact: true}).click();
  await page.getByText('Draft 1 published', {exact: true}).waitFor({timeout: 60000});
  assert((await live.request.get(liveUrl)).headers()['x-merxet-revision'] === a, 'Rollback must restore A');
  await live.reload(); await live.getByRole('heading', {name: 'Extra Virgin Olive Oil', exact: true}).waitFor();
  await page.screenshot({path: 'output/playwright/phase6-mobile-published.png'});
  await live.close();
  console.log('Phase 6 browser flow passed: confirm/cancel, idempotent publish retry, A/B/rollback, direct product reload, buyer link, reload recovery and mobile controls.');
}
